### ISSUE TITLE
Script exiting before finishing

### ISSUE THREAD

**Issue by Colatino** [shooking/ZoomPedalFun#16]
I've been running your zoomzt2-shooking script to get the files (zt2, bmp, json) of all of the fx available for the G1X Four but when it encounters one that is not installed it exits without trying the others. Don't know if it is a bug or a feature.

For my purpose I changed the _getfile_ method to the following:
```python
    def getfile(self, name):
        logging.info("options.receive - getting {}".format(name))
        state = self.file_check(name)
        if (state == False):
#             self.disconnect()
#             sys.exit("Filename doesnt exist")            
            return False
```

And inside _options.receive_ i've included an _if_ condition:
```python
currFX = pedal.getfile(dict(effect)["effect"])
if currFX:
    total_pedal.append(currFX)
    fxLookup[myID, myGID] = j 
    j = j + 1
```
This way it seems to run through all of the installed fx and skip the ones not installed. I didn't check for any new issues caused by this change.

**Comment by Colatino** [comment]
Also, I just uploaded all of the effects available for the G1X-Four (the ones available on Tonelib/Guitarlab) to a repo here on github 
 [https://github.com/Colatino/G1X-Four](url). I used your script to exctract them.

**Comment by shooking** [comment]
Good spot. I dont understand how the extract cannot find the FX (after all it looks at the current state of the pedal). I can add you to the git so you can contribute directly. Bit late here now. Remind me if I haven't don't it by early next week.

**Comment by Colatino** [comment]
Hey @shooking, 
I've been working on the pedal controller for a while and I managed to build somethin usable. It's currently not using a microcontroller but a raspberry pi zero.
The project is [here](http://www.github.com/Colatino/zeropedal) and I uploaded a demo video to youtube [here](https://www.youtube.com/watch?v=D9xH5quKueQ)

**Comment by mungewell** [comment]
@Colatino 

Nice Job. You should definitely share this over at:
https://www.reddit.com/r/zoommultistomp/

There a people there who be very interested in building this.

**Comment by shooking** [comment]
Closing - great piece of Midi hardware.
I finally went the "man in the middle" via a wire / shorting the 3.3v down to 0v via either FS or sending commands to an ESP32.
Works well. There are some parts of a B1XFour that do not seem accessible via MIDI.
