### ISSUE TITLE
Rhythm and Looper for G1Four?

### ISSUE THREAD

**Issue by cjunekim** [shooking/ZoomPedalFun#25]
Hello.

Can you control G1Four's Rhythm and Looper function via USB midi? For example, start, stop, rhythm, and tap tempo.

I think there might be sysex messages. Does anyone know about them?

**Comment by shooking** [comment]
Oh - by GCE-3 I mean the sysex for a G5n, G3n - but to be fair does the Zoom Guitar Lab allow looper and rhythm to be controlled? I know it doesn't expose the pedal (and I have not found sysex for that but someone made a great point ... say you map pedal to param3 ... then if we can read pedal we can map sysex to param 3 scaled by pedal range...)

**Comment by shooking** [comment]
I found the Rhythm on a real G5n is controlled by:
1 - finding the right window (recall you can see 4 FX at a time on a physical machine)
2 - simulating pressing the FS1 - 4 corresponding to where the Rhythm is.

I made a video to demo it BUT this is NOT the same as a real B1XFour/G1XFour that appears to need a physical button press or the physical Man in the Middle i did on video above

Here's video of G5n looper controlled in software
https://youtu.be/CMEuxgvYT9k

it would work same for G3n
