### ISSUE TITLE
Transfer FXs between new multistop series

### ISSUE THREAD

**Issue by Combustao** [shooking/ZoomPedalFun#40]
Now that the entire new Zoom multistomp series has been released [MS-50G+, MS-60B+, MS-70CDR+, MS-80IR+, MS-200D+], will we soon have a hack to transfer effects between them?

They are updates to the old series, but they came with some limitations, which means we have to buy more than one of these pedals, for example, the MS-50G+ does not have cab or IR simulation, the MS-80IR+ only has 3 blocks effect per preset, the MS-70CDR+ does not have amp or drive simulations...

With a possible hack, we would only need to have one of these pedals to access all the features of the new Zoom series.

**Comment by shooking** [comment]
Closing because Mungewell and chums are making excellent progress there on his Zoom zt2
